#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
foods:
    type: rest
    resource: "@AppBundle/Controller/FoodsController.php"
products:
    type: rest
    resource: "routing/products.yml"
brands:
    type: rest
    resource: "@AppBundle/Controller/BrandsController.php"
suppliers:
    type: rest
    resource: "@AppBundle/Controller/SuppliersController.php"
categories:
    type: rest
    resource: "@AppBundle/Controller/CategoriesController.php"
