parameters:

services:
    json_normalizer:
        class: Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    app_bundle.controller.foods_controller:
        class: AppBundle\Controller\FoodsController
        arguments: ['@doctrine']
